apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: parking
  name: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: parking
    spec:
      containers:
        - image: farazff/parking:1.0
          name: parking
          resources:
            limits:
              cpu: 1500m
              ephemeral-storage: 1G
              memory: 600M
            requests:
              cpu: 1500m
              ephemeral-storage: 1G
              memory: 600M
          ports:
            - containerPort: 65432
          envFrom:
            - configMapRef:
                name: parking-config
status: {}
